# Deployment of the React cat application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-cat
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-cat
    spec:
      containers:
        - name: react-cat
          image: 'canada/en:v1.1'
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  ---
# LoadBalancer service deployment. Costs $$$ & so be careful.
apiVersion: v1
kind: Service
metadata:
  name: react-cat
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: react-cat
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
